package com.patentdata.model;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * Generated by Hibernate Tools 4.3.1.Final
 * CitiesId generated by hbm2java
 * @author tonykuo
 *
 */
@Embeddable
public class CitiesId  implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    
    private String name;
    private Serializable location;

    public CitiesId() {
    }

    public CitiesId(String name, Serializable location) {
       this.name = name;
       this.location = location;
    }
   


    @Column(name="name", nullable=false, length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


    @Column(name="location", nullable=false)
    public Serializable getLocation() {
        return this.location;
    }
    
    public void setLocation(Serializable location) {
        this.location = location;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	     return ToStringBuilder.reflectionToString(this);
     }

}

