package com.patentdata.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * Generated by Hibernate Tools 4.3.1.Final
 * Cities generated by hbm2java
 * @author tonykuo
 *
 */
@Entity
@Table(name="cities"
)
public class Cities  implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    
    private CitiesId id;

    public Cities() {
    }

    public Cities(CitiesId id) {
       this.id = id;
    }
   
    @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="name", column=@Column(name="name", nullable=false, length=80) ), 
        @AttributeOverride(name="location", column=@Column(name="location", nullable=false) ) } )
    public CitiesId getId() {
        return this.id;
    }
    
    public void setId(CitiesId id) {
        this.id = id;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	     return ToStringBuilder.reflectionToString(this);
     }

}

