package com.patentdata.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * Generated by Hibernate Tools 4.3.1.Final
 * WeatherId generated by hbm2java
 * @author tonykuo
 *
 */
@Embeddable
public class WeatherId  implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    
    private String city;
    private Integer tempLo;
    private Integer tempHi;
    private Float prcp;
    private Date date;

    public WeatherId() {
    }

    public WeatherId(String city, Integer tempLo, Integer tempHi, Float prcp, Date date) {
       this.city = city;
       this.tempLo = tempLo;
       this.tempHi = tempHi;
       this.prcp = prcp;
       this.date = date;
    }
   


    @Column(name="city", nullable=false, length=80)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }


    @Column(name="temp_lo", nullable=false)
    public Integer getTempLo() {
        return this.tempLo;
    }
    
    public void setTempLo(Integer tempLo) {
        this.tempLo = tempLo;
    }


    @Column(name="temp_hi", nullable=false)
    public Integer getTempHi() {
        return this.tempHi;
    }
    
    public void setTempHi(Integer tempHi) {
        this.tempHi = tempHi;
    }


    @Column(name="prcp", nullable=false, precision=8, scale=8)
    public Float getPrcp() {
        return this.prcp;
    }
    
    public void setPrcp(Float prcp) {
        this.prcp = prcp;
    }


    @Column(name="date", nullable=false, length=13)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	     return ToStringBuilder.reflectionToString(this);
     }

}

